# Generated by Django 5.2.8 on 2025-12-01 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(choices=[('xlsx', 'Excel (.xlsx)'), ('csv', 'CSV (.csv)'), ('pdf', 'PDF (.pdf)'), ('txt', 'Text (.txt)'), ('docx', 'Word (.docx)')], max_length=10)),
                ('is_master', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_json', models.JSONField()),
                ('master_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_master_runs', to='comparison.uploadedfile')),
                ('target_files', models.ManyToManyField(related_name='comparison_target_runs', to='comparison.uploadedfile')),
            ],
        ),
    ]
